---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: nginx
        image: nicholasdille/nginx-hello
