---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: nginx
        image: nicholasdille/nginx-hello
      tolerations:
      - key: "dille.io/reservedFor"
        operator: "Equal"
        value: "web2"
        effect: "NoSchedule"