---
apiVersion: v1
kind: Pod
metadata:
  name: exec
spec:
  containers:
  - name: exec
    image: alpine
    command:
    - /bin/sh
    - -c
    args:
    - touch /tmp/healthy; sleep 10; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
