---
apiVersion: v1
kind: Pod
metadata:
  name: preferred-node-affinity
  labels:
    affinity: preferred
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "dille.io/even"
            operator: In
            values:
            - "yes"
  containers:
  - name: nginx
    image: nicholasdille/nginx-hello
---
apiVersion: v1
kind: Pod
metadata:
  name: required-node-affinity
  labels:
    affinity: required
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dille.io/even
            operator: In
            values:
            - "yes"
  containers:
  - name: nginx
    image: nicholasdille/nginx-hello
