---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: web2
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: local-path-claim
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: data
