---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dummy-pv
  labels:
    storage: dummy
spec:
  capacity:
    storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv/dummy
    type: DirectoryOrCreate
