---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      storage: dummy
