---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: besteffort
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nicholasdille/nginx-hello
