---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burstable
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nicholasdille/nginx-hello
        resources:
          requests:
            cpu: "200m"
            memory: "100Mi"
